/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf --transform 
Files: scene.gltf [31.59KB] > D:\images\simple-robot\scene-transformed.glb [148.59KB] (-370%)
Author: kiliankoe (https://sketchfab.com/kiliankoe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-robot-d560abac003249b293aed39a850dee72
Title: Simple Robot
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry} material={materials.Root} position={[0, 2.357, -0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.879, 0.666, 0.833]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
