/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf --transform 
Files: scene.gltf [30.52KB] > D:\images\gaming_laptop\scene-transformed.glb [1.17MB] (-3734%)
Author: Blue Lantern (https://sketchfab.com/genoris2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-laptop-4e72a2078b3c4a75a821ab09830693fe
Title: Gaming Laptop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[-1.199, 0.096, 0]} rotation={[0, 0, -1.38]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.004']} position={[-1.199, 0.096, 0]} rotation={[0, 0, -1.38]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial002} position={[-1.199, 0.096, 0]} rotation={[0, 0, -1.38]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.010']} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
