/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf --transform 
Files: scene.gltf [4.2KB] > D:\images\mickey-mouse-fbx\scene-transformed.glb [41.91KB] (-898%)
Author: jadiel.ozuno (https://sketchfab.com/jadiel.ozuna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mickey-mouse-fbx-8cfc790775f14c8fbbf386fef1352065
Title: Mickey-mouse-fbx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FUegd_FUegdMat_0.geometry} material={materials.FUegdMat} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
