/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf --transform 
Files: scene.gltf [192.35KB] > D:\images\stylish-robot\scene-transformed.glb [404.58KB] (-110%)
Author: Ahmad Qasem (https://sketchfab.com/ahmadqasem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-robot-0-9-max-cb5013e6151f40279e4d49ae430a1c23
Title: Stylized robot: 0-9 MAX
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bodyMid_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} scale={0.077} />
      <mesh geometry={nodes.screenFace_maxRobot_screen_M_0.geometry} material={materials.maxRobot_screen_M} scale={0.077} />
      <mesh geometry={nodes.screenBack_MAxRobot_screenBack_M_0.geometry} material={materials.MAxRobot_screenBack_M} scale={0.077} />
      <mesh geometry={nodes.neutral_L_maxRobot_eyes_and_emotions_T_0.geometry} material={materials.maxRobot_eyes_and_emotions_T} scale={0.077} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
